#!/bin/bash
# Full 3-dataset x 3-seed runs for the 4 new network-based transfer/privacy methods
# (MEKT, MDMAML, ASFA, SAFE). The 2 new backbones (TIE-EEGNet, KDFNet) are tuned
# separately via tune_networks (LR grid). Results share hustbciml_results_3ds so
# extract_3ds_v2.py picks them up uniformly. Resume-safe (done-markers). One GPU per
# invocation; launch several in parallel across free GPUs.
#   Usage: sweep_newmethods.sh <GPU_ID> <ALGO> [ALGO ...]
set -u
GPU=${1:?gpu id}; shift
METHODS=("$@")
PY=/home/sylyoung/micromamba/envs/syl-work/bin/python
DATA=/home/sylyoung/data
RES=/home/sylyoung/hustbciml_results_3ds
cd /home/sylyoung
export PYTHONUNBUFFERED=1 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 OPENBLAS_NUM_THREADS=4
export CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=$GPU
mkdir -p "$RES"
DATASETS=(BNCI2014001 BNCI2014002 BNCI2015001)
for algo in "${METHODS[@]}"; do
  for ds in "${DATASETS[@]}"; do
    # No dataset substitution. The privacy-preserving table is two-class
    # BNCI2014001 throughout (RESULTS.md: the four-class exploration is a
    # supplementary appendix, not part of this binary benchmark, and is not shown
    # on the web leaderboard). SAFE used to be rewritten to BNCI2014001-4 here,
    # which meant re-running the committed sweep wrote a four-class result
    # (chance 25%) into the headline two-class column (chance 50%), scored
    # against a two-class baseline. The appendix is regenerated by its own script.
    dsrun="$ds"
    for s in 1 2 3; do
      marker="$RES/.done_new_${dsrun}_${algo}_seed${s}"
      if [ -f "$marker" ]; then echo "SKIP $dsrun $algo seed$s (done)"; continue; fi
      echo "===== $dsrun $algo seed$s [$(date '+%H:%M:%S')] ====="
      if $PY -m hustbciml.run --algorithm "$algo" --dataset "$dsrun" --device cuda \
           --seed "$s" --itr 1 --results_dir "$RES" --data_dir "$DATA"; then
        touch "$marker"
      else
        echo "FAILED $dsrun $algo seed$s (continuing)"
      fi
    done
  done
done
echo "NEWSWEEP_DONE gpu$GPU (${METHODS[*]})"
